[package]
name = "retrogram"
version = "0.1.0"
authors = ["David Wendt <dcrkid@yahoo.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
num-traits = "0.2.6"
argparse = "0.2.2"
lazy_static = "1.3.0"
serde = { version="1.0.90", features = ["derive"] }
serde_json = "1.0"
serde_plain = "0.3.0"